### ISSUE TITLE
Bug in group unit

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#102]
```
maasha@edna:~/install/src/SeqScan/benchmark$ time -p seqscan -m 10 -P pat_group/seqscan_aa.pat -V data/Aurpu2p4.faa
seqscan_123.2.23

seqscan -m 10 -P pat_group/seqscan_aa.pat -V data/Aurpu2p4.faa

Options:
  help:           false
  pattern:
  pattern_file:   pat_group/seqscan_aa.pat
  complement:     forward
  direction:      forward
  start:          0
  end:            0
  threads:        1
  score_encoding: Phred33
  score_min:      25
  ambiguate:      false
  match_type:     10
  match_file:
  output:
  overlap:        false
  filter:
  version:        false
  verbose:        true

Patterns:
  [DEN]{20}
Assertion failed: (pos!=max_pos), function Initialize, file /Users/maasha/install/src/SeqScan/src/pu/group_unit.cc, line 37.
Abort trap: 6
real 0.28
user 0.02
sys 0.00
```

**Comment by RasmusFonseca** [comment]
Where is pat_group/seqscan_aa.pat?

**Comment by maasha** [comment]
I have:

maasha@edna:~/install/src/SeqScan/benchmark/pat_group$ cat seqscan_aa.pat
[DEN]{20}
maasha@edna:~/install/src/SeqScan/benchmark/pat_group$ git status
On branch group-benchmark
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

modified:   seqscan_aa.pat
modified:   ../pat_group_neg/seqscan_aa.pat

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by RasmusFonseca** [comment]
> On branch group-benchmark

Got it.

**Comment by RasmusFonseca** [comment]
Bug was in repeatunit. Fixed in branch group-benchmark
