### ISSUE TITLE
Gunzip benchmark/data/chr22.fa.gz

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#12]
We are shipping our benchmark data file gzipped otherwise it is +30Mbytes. Thus the benchmark/seqscan_vs_sfm/Makefile should gunzip this file before benchmarking.

**Comment by maasha** [comment]
This is now done in the benchmark/seqscan_vs_sfm/Makefile, right?

**Comment by RasmusFonseca** [comment]
Yep
