### ISSUE TITLE
Default start position should be 1

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#35]
Currently it is 0, however, the README says it should be 1 and since match positions are 1-indexed.

**Comment by RasmusFonseca** [comment]
Not completely sure what this means. We start matching from the first character of the sequence. Are you saying reported matches are 0-indexed but should be 1-indexed or are you saying that we are missing support for indicating starting position?

**Comment by maasha** [comment]
I am saying that biologist can't count from zero so hits needs to be
1-based. To them zero only makes sense in a situation with no hits = zero
hits. All the examples in the README are 1-based.

I can't remember if --start is implemented.

**Comment by RasmusFonseca** [comment]
Fixed by adding 1 to the position in Match::Print
