### ISSUE TITLE
Non-standard compile instructions

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#4]
What happened to the *nix standard `./compile && make && make install`?

Can't cmake be tricked to conform to the above?

**Comment by RasmusFonseca** [comment]
Probably meant `./configure`. I dont know if autoconf can be generated from CMakeLists. Someone will be tasked with finding out or otherwise knowing

**Comment by maasha** [comment]
doh! `./configure` indeed.

**Comment by RasmusFonseca** [comment]
Ok researched a bit. Even though something is a *nix standard doesn't mean its necessarily good. I'm happy with the cmake setup but googled autotools vs cmake. Scons (python-based and standalone) shows up in the comparison frequently. See

* http://ubuntuforums.org/showthread.php?t=692692
* https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools

In general autotools is dismissed as not supporting cross-platform compilation and being outdated. cmake is hailed as being very easy to use for different IDEs. scons and cmake have their individual followers but, to quote a guy from scons own repo:

"To sum up, my very subjective opinion is that scons is a better idea, but CMake has a stronger implementation" 
- https://bitbucket.org/scons/scons/wiki/SconsVsOtherBuildTools#markdown-header-cmake

I think cmake is widespread enough that we can just use that as-is.
