### ISSUE TITLE
Nasty repeat bug

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#59]
```
seqscan -p "A{2,}" ../benchmark/data/chr22.fa
```

No hits!

**Comment by maasha** [comment]
Missing Unit Test for above ...

**Comment by RasmusFonseca** [comment]
Fixed in develop. Still missing unit test.

**Comment by RasmusFonseca** [comment]
Ok theres even tests now. IT doesn't terminate within reasonable time on chr22, but thats because we don't have an overlap policy yet.
