### ISSUE TITLE
Problem returning start indices for matches

### ISSUE THREAD

**Issue by Telumehtar** [BIO-DIKU/SeqScan#7]
Since PatternUnit::Initialize only takes iterators as arguments, it is difficult to return exact starting indices for matches.

Possible solutions:
* Give Initialize() start position as integer
* Let PatternUnits return relative indices, and let higher-level PatternUnits combine these to exact indices

**Comment by RasmusFonseca** [comment]
Good point. Additional solution:
* Instead of storing an integer position just store an iterator to the start position. When printing from the main app it will be easy to get the integer position

**Comment by RasmusFonseca** [comment]
My suggestion was a slight modification of your last suggestion. Its implemented
