### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by maasha** [BIO-DIKU/SeqScan#8]
I suggest moving the tests directory up one level ala:

http://stackoverflow.com/questions/2360734/whats-a-good-directory-structure-for-larger-c-projects-using-makefile

That allows a simple mirrored set of src and test files:

```
src/
src/io.cc
...
src/pu/
src/pu/tfna.cc
...
tests/
tests/test_io.cc
...
tests/pu/
tests/pu/test_tfna.cc
...
```

**Comment by RasmusFonseca** [comment]
Sounds good to me.

2015-09-14 11:38 GMT+02:00 Martin Asser Hansen <notifications@github.com>:
